import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
// Import the functions you need from the SDKs you need
import { initializeApp } from "firebase/app";
import { getAnalytics } from "firebase/analytics";
// TODO: Add SDKs for Firebase products that you want to use
// https://firebase.google.com/docs/web/setup#available-libraries

// Your web app's Firebase configuration
// For Firebase JS SDK v7.20.0 and later, measurementId is optional
const firebaseConfig = {
  apiKey: "AIzaSyCEktV8r5lGbTlS0SlIugQtWkq9ExH6QMs",
  authDomain: "bdg-in.firebaseapp.com",
  projectId: "bdg-in",
  storageBucket: "bdg-in.appspot.com",
  messagingSenderId: "226404756457",
  appId: "1:226404756457:web:e3bbab7968635a7f31b978",
  measurementId: "G-5EZYBNZG0C"
};

// Initialize Firebase
const app = initializeApp(firebaseConfig);
const analytics = getAnalytics(app);

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Bdg_In',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
